import Head from 'next/head'
import Image from 'next/image';
import styles from '@/styles/Home.module.css'
import Footer from '@/components/Footer'
import Button from '@/components/Button'

export default function Home() {
  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>

        <title>X. It's what's happening / X</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/fav icon.jpeg" />

      </Head>

      <main className={`${styles.main}`}>
        <div>

        </div>
          <div className={styles.xLogo}>
            <Image className='img-fluid' src='/images/logo.png' alt='Logo' width={300} height={275}/>
          </div>

          <div className={`${styles.mainContent}`}>
            <h1 className={`${styles.h1}`}>Happening now</h1>
            <h2 className={`${styles.h2}`}>Join today.</h2>

            <button className={styles.button}>
              <Image className={styles.imageGoogle} src='/images/google logo.png' width={17} height={17} />
              <span className={styles.googleText}>Sign up with Google</span>
            </button>
            <button className={styles.button}>
              <Image className={styles.imageApple} src='/images/apple logo.png' width={21} height={21} />
              <span className={styles.appleText}>Sign up with Apple</span>
            </button>

            <p className={styles.or}> ━━━━━━━━ or ━━━━━━━━━</p>

            <Button title="Create account" textColor="white" borderColor="none"/>

            <p className={styles.agreement}>By signing up, you agree to the <a href='#' className={styles.policy}>Terms of Service</a> <br/><a href='#' className={styles.policy}>Privacy Policy</a>, including <a href='#' className={styles.policy}>Cookie Use</a>.</p>

            <h3 className={styles.h3}>Already have an account?</h3>

            <Button title="Sign in" color="white"/>         
          </div>

{/*  */}
      </main>
    </>
  )
}